language: ruby
sudo: required
dist: trusty
services:
  - docker
env:
  matrix:
    - DOCKER_COMPOSE_VERSION=1.24.1
    - DOCKER_COMPOSE_VERSION=1.24.0
    - DOCKER_COMPOSE_VERSION=1.23.2
    - DOCKER_COMPOSE_VERSION=1.23.1
    - DOCKER_COMPOSE_VERSION=1.23.0
    - DOCKER_COMPOSE_VERSION=1.22.0
    - DOCKER_COMPOSE_VERSION=1.21.2
    - DOCKER_COMPOSE_VERSION=1.21.1
    - DOCKER_COMPOSE_VERSION=1.21.0
    - DOCKER_COMPOSE_VERSION=1.20.1
    - DOCKER_COMPOSE_VERSION=1.20.0
    - DOCKER_COMPOSE_VERSION=1.19.0
    - DOCKER_COMPOSE_VERSION=1.18.0
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo service mysql stop
script:
  - chmod +x bin/*
  - bin/setup
  - bin/ps
  - bin/cli php -v
  - bin/deploy-mode developer
  - bin/cache clean
  - bin/reindex
  - bin/module
  - bin/xdebug enable
  - bin/xdebug disable
  - bin/redis-setup all
  - bin/nginx-check
  - bin/nginx-reload
  - bin/magento
  - bin/logs
  - bin/docker
  - bin/docker-compose
  - bin/revive
  - bin/stop
  - bin/start
  - bin/up
  - bin/down
  - bin/destroy
