version: "3.7"
networks:
  backend:
    driver: bridge

volumes:
  magento2:
  database:

services:

  magento:
    image: tiagosampaio/magento-opensource:2.3.2
    container_name: magento
    volumes:
      - magento2:/magento2
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: builders/php/Dockerfile
    container_name: php
    restart: on-failure
    volumes:
      - magento2:/var/www/html/magento2
      - ./sites/magento2/app/code:/var/www/html/magento2/app/code
      - ./sites/magento2/app/design:/var/www/html/magento2/app/design
#      - ./sites/magento2/generated:/var/www/html/magento2/generated
      - ./sites/magento2/var/log:/var/www/html/magento2/var/log
      - ./sites/magento2/var/report:/var/www/html/magento2/var/report
      - ./builders/scripts/:/var/scripts/
#      - ./sites/magento2:/var/www/html/magento2:cached
#      - ./conf/php/fpm:/var/local/etc
    environment:
      - MAGENTO_VERSION=2.3.2
      - MAGENTO_EDITION="Open Source"
      - MAGENTO_BASE_URL=http://dev.magento2.com
      - MAGENTO_ADMIN_FRONTNAME=admin
      - MAGENTO_ADMIN_FIRSTNAME=Magento
      - MAGENTO_ADMIN_LASTNAME=User
      - MAGENTO_ADMIN_EMAIL=magento@magento.com
      - MAGENTO_ADMIN_USER=magento
      - MAGENTO_ADMIN_PASSWORD=admin123
      - MAGENTO_LANGUAGE=en_US
      - MAGENTO_CURRENCY=USD
      - MAGENTO_TIMEZONE=America/Sao_Paulo
      - MAGENTO_USE_REWRITES=1
    networks:
      - backend
    links:
      - redis

  nginx:
    image: nginx:1.17
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    volumes:
      - magento2:/var/www/html/magento2
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/
    environment:
      - NGINX_HOST=dev.magento2.com
      - NGINX_PORT=80
    networks:
      - backend
    links:
      - php
    working_dir: /var/www/html/magento2
    # command: /bin/bash -c "envsubst < /var/tmp/magento2.conf > /etc/nginx/conf.d/magento2.conf && exec nginx -g 'daemon off;'"

  database:
    image: percona:latest
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento_pass
      MYSQL_DATABASE: magento2
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:6.8.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backend

  queue:
    image: rabbitmq:3-management
    container_name: queue
    environment:
      RABBITMQ_DEFAULT_USER: magento
      RABBITMQ_DEFAULT_PASS: magento2
    ports:
      - "15672:15672"
    networks:
      - backend

  varnish:
    image: varnish:latest
    container_name: varnish
    restart: on-failure
    volumes:
      - ./conf/varnish:/etc/varnish
    ports:
      - "8080:80"
    networks:
      - backend
