version: "3.7"

networks:
  backend:
    driver: bridge

services:

  magento:
    image: tiagosampaio/magento-opensource:2.3.2
    container_name: magento
    networks:
      - backend

  php:
    image: tiagosampaio/magento2-php:7.2-fpm
    container_name: php
    restart: on-failure
    depends_on:
      - database
      - magento
    networks:
      - backend
#    links:
#      - redis

  nginx:
    image: nginx:1.17
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    networks:
      - backend
    depends_on:
      - php
    links:
      - php
    working_dir: /var/www/html/magento2
    command: /bin/bash -c "envsubst < /var/tmp/magento2.conf > /etc/nginx/conf.d/magento2.conf && exec nginx -g 'daemon off;'"

  database:
    image: percona:latest
    container_name: database
    restart: on-failure
    ports:
      - "3306:3306"
    networks:
      - backend

#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - "6379:6379"
#    networks:
#      - backend

#  elasticsearch:
#    image: elasticsearch:6.8.2
#    container_name: elasticsearch
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    networks:
#      - backend

#  queue:
#    image: rabbitmq:3-management
#    container_name: queue
#    environment:
#      RABBITMQ_DEFAULT_USER: magento
#      RABBITMQ_DEFAULT_PASS: magento2
#    ports:
#      - "15672:15672"
#    networks:
#      - backend

#  varnish:
#    image: varnish:latest
#    container_name: varnish
#    restart: on-failure
#    volumes:
#      - ./conf/varnish:/etc/varnish
#    ports:
#      - "8080:80"
#    networks:
#      - backend
