# Tiago Sampaio's Docker Configuration for Magento 2 (https://github.com/tiagosampaio/magento2-devstack)

version: "3.3"

volumes:
  database:

services:

  php:
    volumes:
      - ../../sites/magento2:/var/www/html/magento2
    env_file:
      - ../env/magento.env
      - ../env/db.env
      - ../../.env

  nginx:
    volumes:
      - ../../sites/magento2:/var/www/html/magento2
      - ../conf/nginx/conf.d/:/etc/nginx/conf.d/
      - ../conf/nginx/template/magento2.conf:/var/tmp/magento2.conf
      - ../../var/storage/logs/nginx:/var/log/nginx
    env_file:
      - ../env/magento.env
      - ../../.env

  database:
    env_file:
      - ../env/db.env
      - ../../.env
    volumes:
      - database:/var/lib/mysql

  mail:
    image: mailhog/mailhog
    container_name: mail
    ports:
      - "1025:1025"
      - "8025:8025"
