# Tiago Sampaio's Docker Configuration for Magento 2 (https://github.com/tiagosampaio/magento2-devstack)

version: "3.3"

volumes:
  magento2:
  database:

services:

  php:
    volumes:
      - magento2:/var/www/html/magento2
#      - ../../sites/magento2:/root/magento2
      - ../../var/magento/releases/:/var/magento/releases/
      - ../../sites/magento2/app/code:/var/www/html/magento2/app/code
      - ../../sites/magento2/app/design:/var/www/html/magento2/app/design
#      - ./sites/magento2/generated:/var/www/html/magento2/generated
      - ../../sites/magento2/var/log:/var/www/html/magento2/var/log
      - ../../sites/magento2/var/report:/var/www/html/magento2/var/report
#      - ./sites/magento2:/var/www/html/magento2:cached
#      - ./conf/php/fpm:/var/local/etc
    env_file:
      - ../env/magento.env
      - ../env/db.env
      - ../../.env

  nginx:
    volumes:
      - magento2:/var/www/html/magento2
      - ../conf/nginx/conf.d/:/etc/nginx/conf.d/
      - ../conf/nginx/template/magento2.conf:/var/tmp/magento2.conf
      - ../../var/storage/logs/nginx:/var/log/nginx
    env_file:
      - ../env/magento.env
      - ../../.env

  database:
    env_file:
      - ../env/db.env
      - ../../.env
    volumes:
      - database:/var/lib/mysql

  mail:
    image: mailhog/mailhog
    container_name: mail
    ports:
      - "1025:1025"
      - "8025:8025"
